const productdata = {
    products: [
      {
        productid: 42419,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "White",
        usage: "Casual",
        name: "Gini and Jony Girls Knit White Top",
        image: "/images/42419.jpg",
        slug: "gini-and-jony-girls-knit-white-top",
        price: 3937,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 71,
        brand: "Nike",
        reviews: 8
      },
      {
        productid: 34009,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "Black",
        usage: "Casual",
        name: "Gini and Jony Girls Black Top",
        image: "/images/34009.jpg",
        slug: "gini-and-jony-girls-black-top",
        price: 1173,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 65,
        brand: "Nike",
        reviews: 7
      },
      {
        productid: 40143,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "Blue",
        usage: "Casual",
        name: "Gini and Jony Girls Pretty Blossom Blue Top",
        image: "/images/40143.jpg",
        slug: "gini-and-jony-girls-pretty-blossom-blue-top",
        price: 9386,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 75,
        brand: "Nike",
        reviews: 3
      },
      {
        productid: 23623,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "Pink",
        usage: "Casual",
        name: "Doodle Kids Girls Pink I love Shopping Top",
        image: "/images/23623.jpg",
        slug: "doodle-kids-girls-pink-i-love-shopping-top",
        price: 4684,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 2,
        countInStock: 78,
        brand: "Nike",
        reviews: 2
      },
      {
        productId: 47154,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Bottomwear",
        producttype: "Capris",
        colour: "Black",
        usage: "Casual",
        name: "Gini and Jony Girls Black Capris",
        image: "/images/47154.jpg",
        slug: "gini-and-jony-girls-black-capris",
        price: 3467,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 2,
        countInStock: 45,
        brand: "Nike",
        reviews: 8
      },
      {
        productid: 25520,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "White",
        usage: "Casual",
        name: "Doodle Kids Girls City Chic White Top",
        image: "/images/25520.jpg",
        slug: "doodle-kids-girls-city-chic-white-top",
        price: 6024,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 83,
        brand: "Nike",
        reviews: 5
      },
      {
        productid: 31120,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "Pink",
        usage: "Casual",
        name: "Palm Tree Girls Pink Top",
        image: "/images/31120.jpg",
        slug: "palm-tree-girls-pink-top",
        price: 7955,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 57,
        brand: "Nike",
        reviews: 2
      },
      {
        productid: 31118,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "Red",
        usage: "Casual",
        name: "Gini and Jony Girls Red Top",
        image: "/images/31118.jpg",
        slug: "gini-and-jony-girls-red-top",
        price: 5872,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 91,
        brand: "Nike",
        reviews: 3
      },
      {
        productid: 54923,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Bottomwear",
        producttype: "Capris",
        colour: "Olive",
        usage: "Casual",
        name: "Do u speak Green Girls Olive 3/4 Pant",
        image: "/images/54923.jpg",
        slug: "do-u-speak-green-girls-olive-3/4-pant",
        price: 5226,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 97,
        brand: "Nike",
        reviews: 6
      },
      {
        productid: 31127,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Dress",
        producttype: "Dresses",
        colour: "Black",
        usage: "Casual",
        name: "Gini and Jony Girls Black Dress",
        image: "/images/31127.jpg",
        slug: "gini-and-jony-girls-black-dress",
        price: 900,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 76,
        brand: "Nike",
        reviews: 2
      },
      {
        productid: 47153,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Bottomwear",
        producttype: "Capris",
        colour: "Pink",
        usage: "Casual",
        name: "Gini and Jony Girls Pink Capris",
        image: "/images/47153.jpg",
        slug: "gini-and-jony-girls-pink-capris",
        price: 1394,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 62,
        brand: "Nike",
        reviews: 5
      },
      {
        productid: 40144,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "Pink",
        usage: "Casual",
        name: "Gini and Jony Girls Pretty Blossom Pink Top",
        image: "/images/40144.jpg",
        slug: "gini-and-jony-girls-pretty-blossom-pink-top",
        price: 2522,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 99,
        brand: "Nike",
        reviews: 1
      },
      {
        productid: 23624,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "White",
        usage: "Casual",
        name: "Doodle Kids Girls White I love Shopping Top",
        image: "/images/23624.jpg",
        slug: "doodle-kids-girls-white-i-love-shopping-top",
        price: 8758,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 2,
        countInStock: 80,
        brand: "Nike",
        reviews: 1
      },
      {
        productid: 34693,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Bottomwear",
        producttype: "Shorts",
        colour: "Pink",
        usage: "Casual",
        name: "Allen Solly Kids Girls Poplin Pink Shorts",
        image: "/images/34693.jpg",
        slug: "allen-solly-kids-girls-poplin-pink-shorts",
        price: 4395,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 96,
        brand: "Nike",
        reviews: 7
      },
      {
        productid: 4718,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Yellow",
        usage: "Casual",
        name: "Disney Kids Girl's Summer Fun Fair Yellow Teen Kidswear",
        image: "/images/4718.jpg",
        slug: "disney-kids-girl's-summer-fun-fair-yellow-teen-kidswear",
        price: 9780,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 53,
        brand: "Nike",
        reviews: 8
      },
      {
        productid: 36750,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Dress",
        producttype: "Dresses",
        colour: "Navy Blue",
        usage: "Casual",
        name: "Little Miss Girls Chatterbox Navy Blue Dress",
        image: "/images/36750.jpg",
        slug: "little-miss-girls-chatterbox-navy-blue-dress",
        price: 6124,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 79,
        brand: "Nike",
        reviews: 7
      },
      {
        productid: 34007,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tops",
        colour: "Pink",
        usage: "Casual",
        name: "Gini and Jony Girls Pink Top",
        image: "/images/34007.jpg",
        slug: "gini-and-jony-girls-pink-top",
        price: 4660,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 92,
        brand: "Nike",
        reviews: 3
      },
      {
        productid: 31129,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Dress",
        producttype: "Dresses",
        colour: "Magenta",
        usage: "Casual",
        name: "Giny and Jony Girls Printed White & Pink Dress",
        image: "/images/31129.jpg",
        slug: "giny-and-jony-girls-printed-white-&-pink-dress",
        price: 2277,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 83,
        brand: "Nike",
        reviews: 5
      },
      {
        productid: 4720,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Yellow",
        usage: "Casual",
        name: "Disney Kids Girl's Fun In The Fair Yellow Teen Kidswear",
        image: "/images/4720.jpg",
        slug: "disney-kids-girl's-fun-in-the-fair-yellow-teen-kidswear",
        price: 3747,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 84,
        brand: "Nike",
        reviews: 6
      },
      {
        productid: 17612,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Grey",
        usage: "Casual",
        name: "Doodle Cute Girls  Grey Tshirt",
        image: "/images/17612.jpg",
        slug: "doodle-cute-girls--grey-tshirt",
        price: 4281,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 59,
        brand: "Addidas",
        reviews: 8
      },
      {
        productid: 50723,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Dress",
        producttype: "Dresses",
        colour: "Blue",
        usage: "Casual",
        name: "Doodle Girls Blue Printed Dress",
        image: "/images/50723.jpg",
        slug: "doodle-girls-blue-printed-dress",
        price: 3546,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 70,
        brand: "Addidas",
        reviews: 3
      },
      {
        productid: 33271,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Bottomwear",
        producttype: "Skirts",
        colour: "Red",
        usage: "Casual",
        name: "Gini and Jony Girls Red Skirt",
        image: "/images/33271.jpg",
        slug: "gini-and-jony-girls-red-skirt",
        price: 8568,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 82,
        brand: "Addidas",
        reviews: 4
      },
      {
        productid: 41007,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Bottomwear",
        producttype: "Shorts",
        colour: "Navy Blue",
        usage: "Casual",
        name: "Gini and Jony Girls Woven Navy Blue Shorts",
        image: "/images/41007.jpg",
        slug: "gini-and-jony-girls-woven-navy-blue-shorts",
        price: 6118,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 54,
        brand: "Addidas",
        reviews: 6
      },
      {
        productid: 46813,
        gender: "Girls",
        category: "Apparel",
        subcategory: "Bottomwear",
        producttype: "Skirts",
        colour: "Pink",
        usage: "Casual",
        name: "Gini and Jony Girls Pink Skirt",
        image: "/images/46813.jpg",
        slug: "gini-and-jony-girls-pink-skirt",
        price: 4828,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 81,
        brand: "Addidas",
        reviews: 7
      },
      {
        productid: 4729,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Green",
        usage: "Casual",
        name: "Disney Kids Boy's Crew Sea Life Sialing Green Teen Kidswear",
        image: "/images/4729.jpg",
        slug: "disney-kids-boy's-crew-sea-life-sialing-green-teen-kidswear",
        price: 4624,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 63,
        brand: "Addidas",
        reviews: 8
      },
      {
        productid: 8322,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Blue",
        usage: "Casual",
        name: "Doodle Boy's Route 66 Biker Blue Teen Kidswear",
        image: "/images/8322.jpg",
        slug: "doodle-boy's-route-66-biker-blue-teen-kidswear",
        price: 4238,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 72,
        brand: "Addidas",
        reviews: 7
      },
      {
        productid: 34036,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Shirts",
        colour: "Blue",
        usage: "Casual",
        name: "Palm Tree Boys Check Blue Shirt",
        image: "/images/34036.jpg",
        slug: "palm-tree-boys-check-blue-shirt",
        price: 9849,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 89,
        brand: "Addidas",
        reviews: 2
      },
      {
        productid: 8325,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Yellow",
        usage: "Casual",
        name: "Doodle Boy's Athletic 77 Dept Yellow Teen Kidswear",
        image: "/images/8325.jpg",
        slug: "doodle-boy's-athletic-77-dept-yellow-teen-kidswear",
        price: 7906,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 2,
        countInStock: 93,
        brand: "Addidas",
        reviews: 2
      },
      {
        productid: 40947,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Red",
        usage: "Casual",
        name: "Gini and Jony Boys Core Red T-shirt",
        image: "/images/40947.jpg",
        slug: "gini-and-jony-boys-core-red-t-shirt",
        price: 979,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 77,
        brand: "Addidas",
        reviews: 1
      },
      {
        productid: 34031,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Shirts",
        colour: "Blue",
        usage: "Casual",
        name: "Gini and Jony Boys Check Blue Shirt",
        image: "/images/34031.jpg",
        slug: "gini-and-jony-boys-check-blue-shirt",
        price: 2544,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 2,
        countInStock: 54,
        brand: "Addidas",
        reviews: 3
      },
      {
        productid: 40978,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Red",
        usage: "Casual",
        name: "Gini and Jony Boys United Red T-shirt",
        image: "/images/40978.jpg",
        slug: "gini-and-jony-boys-united-red-t-shirt",
        price: 5134,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 48,
        brand: "Addidas",
        reviews: 3
      },
      {
        productid: 34038,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Shirts",
        colour: "Red",
        usage: "Casual",
        name: "Gini and Jony Boys Check Red Shirt",
        image: "/images/34038.jpg",
        slug: "gini-and-jony-boys-check-red-shirt",
        price: 5200,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 45,
        brand: "Zara",
        reviews: 7
      },
      {
        productid: 40985,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "White",
        usage: "Casual",
        name: "Gini and Jony Boys United White T-shirt",
        image: "/images/40985.jpg",
        slug: "gini-and-jony-boys-united-white-t-shirt",
        price: 3158,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 76,
        brand: "Zara",
        reviews: 1
      },
      {
        productid: 31111,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Bottomwear",
        producttype: "Jeans",
        colour: "Black",
        usage: "Casual",
        name: "Gini and Jony Boys Solid Black Jeans",
        image: "/images/31111.jpg",
        slug: "gini-and-jony-boys-solid-black-jeans",
        price: 8290,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 98,
        brand: "Zara",
        reviews: 5
      },
      {
        productid: 10054,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "Blue",
        usage: "Sports",
        name: "Reebok Kids Kkr Boy's Premium Blue Jerseys",
        image: "/images/10054.jpg",
        slug: "reebok-kids-kkr-boy's-premium-blue-jerseys",
        price: 2365,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 72,
        brand: "Zara",
        reviews: 1
      },
      {
        productid: 17615,
        gender: "Boys",
        category: "Apparel",
        subcategory: "Topwear",
        producttype: "Tshirts",
        colour: "White",
        usage: "Casual",
        name: "Doodle Boys living Upto White Tshirt",
        image: "/images/17615.jpg",
        slug: "doodle-boys-living-upto-white-tshirt",
        price: 8295,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 52,
        brand: "Zara",
        reviews: 6
      },
      {
        productid: 9204,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Casual Shoes",
        colour: "Black",
        usage: "Casual",
        name: "Puma Men Future Cat Remix SF Black Casual Shoes",
        image: "/images/9204.jpg",
        slug: "puma-men-future-cat-remix-sf-black-casual-shoes",
        price: 5620,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 2,
        countInStock: 85,
        brand: "Zara",
        reviews: 2
      },
      {
        productid: 18653,
        gender: "Men",
        category: "Footwear",
        subcategory: "Flip Flops",
        producttype: "Flip Flops",
        colour: "Black",
        usage: "Casual",
        name: "Fila Men Cush Flex Black Slippers",
        image: "/images/18653.jpg",
        slug: "fila-men-cush-flex-black-slippers",
        price: 1593,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 93,
        brand: "Zara",
        reviews: 3
      },
      {
        productid: 12967,
        gender: "Men",
        category: "Footwear",
        subcategory: "Sandal",
        producttype: "Sandals",
        colour: "Black",
        usage: "Casual",
        name: "ADIDAS Men Spry M Black Sandals",
        image: "/images/12967.jpg",
        slug: "adidas-men-spry-m-black-sandals",
        price: 7542,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 70,
        brand: "Zara",
        reviews: 7
      },
      {
        productid: 9036,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Formal Shoes",
        colour: "Black",
        usage: "Formal",
        name: "Buckaroo Men Flores Black Formal Shoes",
        image: "/images/9036.jpg",
        slug: "buckaroo-men-flores-black-formal-shoes",
        price: 6208,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 55,
        brand: "Zara",
        reviews: 7
      },
      {
        productid: 39988,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Casual Shoes",
        colour: "White",
        usage: "Casual",
        name: "Gas Men Europa White Shoes",
        image: "/images/39988.jpg",
        slug: "gas-men-europa-white-shoes",
        price: 5240,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 71,
        brand: "Zara",
        reviews: 5
      },
      {
        productid: 3168,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Sports Shoes",
        colour: "White",
        usage: "Sports",
        name: "Nike Men's Incinerate MSL White Blue Shoe",
        image: "/images/3168.jpg",
        slug: "nike-men's-incinerate-msl-white-blue-shoe",
        price: 2823,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 93,
        brand: "Zara",
        reviews: 6
      },
      {
        productid: 10268,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Formal Shoes",
        colour: "Black",
        usage: "Formal",
        name: "Clarks Men Hang Work Leather Black Formal Shoes",
        image: "/images/10268.jpg",
        slug: "clarks-men-hang-work-leather-black-formal-shoes",
        price: 8806,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 82,
        brand: "Zara",
        reviews: 1
      },
      {
        productid: 59435,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Formal Shoes",
        colour: "Black",
        usage: "Formal",
        name: "Arrow Men Black Formal Shoes",
        image: "/images/59435.jpg",
        slug: "arrow-men-black-formal-shoes",
        price: 6349,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 59,
        brand: "Zara",
        reviews: 5
      },
      {
        productid: 22198,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Casual Shoes",
        colour: "Black",
        usage: "Casual",
        name: "Timberland Men Black Casual Shoes",
        image: "/images/22198.jpg",
        slug: "timberland-men-black-casual-shoes",
        price: 2201,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 2,
        countInStock: 86,
        brand: "Zara",
        reviews: 3
      },
      {
        productid: 29570,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Casual Shoes",
        colour: "Purple",
        usage: "Casual",
        name: "Vans Men Classic Slip-On Purple & Black Shoes",
        image: "/images/29570.jpg",
        slug: "vans-men-classic-slip-on-purple-&-black-shoes",
        price: 9178,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 46,
        brand: "Zara",
        reviews: 5
      },
      {
        productid: 6628,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Sports Shoes",
        colour: "White",
        usage: "Sports",
        name: "ADIDAS Men's Lowell White Silver Shoe",
        image: "/images/6628.jpg",
        slug: "adidas-men's-lowell-white-silver-shoe",
        price: 1685,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 46,
        brand: "Zara",
        reviews: 7
      },
      {
        productid: 26538,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Casual Shoes",
        colour: "Red",
        usage: "Casual",
        name: "ID Men Red Shoes",
        image: "/images/26538.jpg",
        slug: "id-men-red-shoes",
        price: 3158,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 51,
        brand: "Zara",
        reviews: 5
      },
      {
        productid: 49495,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Casual Shoes",
        colour: "Khaki",
        usage: "Casual",
        name: "Vans Men Khaki Shoes",
        image: "/images/49495.jpg",
        slug: "vans-men-khaki-shoes",
        price: 2738,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 53,
        brand: "Zara",
        reviews: 4
      },
      {
        productid: 19123,
        gender: "Men",
        category: "Footwear",
        subcategory: "Flip Flops",
        producttype: "Flip Flops",
        colour: "Silver",
        usage: "Casual",
        name: "Lotto Men XL Water Man Silver Slippers",
        image: "/images/19123.jpg",
        slug: "lotto-men-xl-water-man-silver-slippers",
        price: 1046,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 51,
        brand: "Zara",
        reviews: 1
      },
      {
        productid: 43369,
        gender: "Men",
        category: "Footwear",
        subcategory: "Flip Flops",
        producttype: "Flip Flops",
        colour: "Black",
        usage: "Casual",
        name: "Reebok Men Black Possession Flip Flops",
        image: "/images/43369.jpg",
        slug: "reebok-men-black-possession-flip-flops",
        price: 5213,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 5,
        countInStock: 80,
        brand: "Zara",
        reviews: 4
      },
      {
        productid: 33822,
        gender: "Men",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Sports Shoes",
        colour: "White",
        usage: "Sports",
        name: "Puma Men Axis White & Grey Sports Shoes",
        image: "/images/33822.jpg",
        slug: "puma-men-axis-white-&-grey-sports-shoes",
        price: 3483,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 65,
        brand: "Zara",
        reviews: 4
      },
      {
        productid: 11940,
        gender: "Men",
        category: "Footwear",
        subcategory: "Sandal",
        producttype: "Sandals",
        colour: "Black",
        usage: "Casual",
        name: "Ganuchi Men Casual Black Sandals",
        image: "/images/11940.jpg",
        slug: "ganuchi-men-casual-black-sandals",
        price: 7366,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 2,
        countInStock: 64,
        brand: "Zara",
        reviews: 1
      },
      {
        productid: 59051,
        gender: "Women",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Flats",
        colour: "Black",
        usage: "Casual",
        name: "Carlton London Women Black & Gold Toned Flats",
        image: "/images/59051.jpg",
        slug: "carlton-london-women-black-&-gold-toned-flats",
        price: 8295,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 60,
        brand: "Zara",
        reviews: 2
      },
      {
        productid: 2886,
        gender: "Women",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Flats",
        colour: "Brown",
        usage: "Casual",
        name: "Catwalk Women Leather Brown Flats",
        image: "/images/2886.jpg",
        slug: "catwalk-women-leather-brown-flats",
        price: 2293,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 94,
        brand: "Zara",
        reviews: 8
      },
      {
        productid: 54118,
        gender: "Women",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Heels",
        colour: "Black",
        usage: "Casual",
        name: "Rocia Women Black Flats",
        image: "/images/54118.jpg",
        slug: "rocia-women-black-flats",
        price: 9967,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 67,
        brand: "Zara",
        reviews: 6
      },
      {
        productid: 2872,
        gender: "Women",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Heels",
        colour: "Brown",
        usage: "Casual",
        name: "Catwalk Women Leather Flats",
        image: "/images/2872.jpg",
        slug: "catwalk-women-leather-flats",
        price: 9394,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 56,
        brand: "Zara",
        reviews: 4
      },
      {
        productid: 8574,
        gender: "Women",
        category: "Footwear",
        subcategory: "Sandal",
        producttype: "Sandals",
        colour: "Pink",
        usage: "Casual",
        name: "Crocs Dora Boots Pink Sandals",
        image: "/images/8574.jpg",
        slug: "crocs-dora-boots-pink-sandals",
        price: 9953,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 53,
        brand: "Zara",
        reviews: 4
      },
      {
        productid: 11518,
        gender: "Women",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Heels",
        colour: "Grey",
        usage: "Casual",
        name: "Catwalk Women Gun Metal Grey Heels",
        image: "/images/11518.jpg",
        slug: "catwalk-women-gun-metal-grey-heels",
        price: 3905,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 51,
        brand: "Gucci",
        reviews: 8
      },
      {
        productid: 49839,
        gender: "Women",
        category: "Footwear",
        subcategory: "Flip Flops",
        producttype: "Flip Flops",
        colour: "Red",
        usage: "Casual",
        name: "iPanema Women Red Flip Flops",
        image: "/images/49839.jpg",
        slug: "ipanema-women-red-flip-flops",
        price: 6629,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 74,
        brand: "Gucci",
        reviews: 5
      },
      {
        productid: 2618,
        gender: "Women",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Flats",
        colour: "Silver",
        usage: "Casual",
        name: "Carlton London Women Silver Wedge Sandal",
        image: "/images/2618.jpg",
        slug: "carlton-london-women-silver-wedge-sandal",
        price: 5639,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 1,
        countInStock: 65,
        brand: "Gucci",
        reviews: 6
      },
      {
        productid: 47530,
        gender: "Women",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Flats",
        colour: "Copper",
        usage: "Casual",
        name: "Portia Women Copper-Toned & Brown Sandals",
        image: "/images/47530.jpg",
        slug: "portia-women-copper-toned-&-brown-sandals",
        price: 7823,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 4,
        countInStock: 45,
        brand: "Gucci",
        reviews: 5
      },
      {
        productid: 54127,
        gender: "Women",
        category: "Footwear",
        subcategory: "Shoes",
        producttype: "Heels",
        colour: "Black",
        usage: "Casual",
        name: "Rocia Women Black Heels",
        image: "/images/54127.jpg",
        slug: "rocia-women-black-heels",
        price: 3536,
        description: "It is a long established fact that a reader will be distracted by thereadable content of a page when looking at its layout. The point of usingLorem Ipsum is that it has a more-or-less normal distribution of letters.",
        rating: 3,
        countInStock: 53,
        brand: "Gucci",
        reviews: 7
      }
     ]
}

export default productdata;